server {
    server_name impacta.pinguinoseguro.cl app-impacta.pinguinoseguro.cl;

    root /var/www/impacta.pinguinoseguro.cl;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://10.89.1.12:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/pinguinoseguro.cl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pinguinoseguro.cl/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    server_name api-impacta.pinguinoseguro.cl;

    location / {
        proxy_pass http://10.89.1.12:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/pinguinoseguro.cl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pinguinoseguro.cl/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    server_name impacta.pinguinoseguro.cl app-impacta.pinguinoseguro.cl api-impacta.pinguinoseguro.cl;
    listen 80;
    return 301 https://$host$request_uri;
}
